package awsplugin.cloudformation

enum StackStatus {
    CREATE_COMPLETE,
    CREATE_IN_PROGRESS,
    CREATE_FAILED,
    DELETE_COMPLETE,
    DELETE_FAILED,
    DELETE_IN_PROGRESS,
    ROLLBACK_COMPLETE,
    ROLLBACK_FAILED,
    ROLLBACK_IN_PROGRESS,
    UPDATE_COMPLETE,
    UPDATE_COMPLETE_CLEANUP_IN_PROGRESS,
    UPDATE_IN_PROGRESS,
    UPDATE_ROLLBACK_COMPLETE,
    UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS,
    UPDATE_ROLLBACK_FAILED,
    UPDATE_ROLLBACK_IN_PROGRESS,
    NON_EXISTENT
}
